circle ci was updated

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -17,14 +17,11 @@ parameters:
     type: boolean
     default: true
 
-
 executors:
   test-executor:
     docker:
       - image: cimg/openjdk:11.0.19-browsers
-
     working_directory: ~/SelenideProject
-
     environment:
       MAVEN_OPTS: -Xmx4096m
 
@@ -33,27 +30,38 @@ commands:
   restore-and-save-cache:
     description: "Restore and save cache"
     steps:
+      - run:
+          name: Ensure working directory exists
+          command: mkdir -p ~/SelenideProject
+
+      - checkout  # Загружаем код перед кешем
+
+      - run:
+          name: Verify if pom.xml exists
+          command: |
+            if [ ! -f pom.xml ]; then
+              echo "ERROR: pom.xml not found!"
+              exit 1
+            fi
+
       - restore_cache:
           keys:
-            - v1-dependencies-{{ checksum "pom.xml" }}
-            - v1-dependencies-
+            - v2-dependencies-{{ checksum "pom.xml" }}
+            - v2-dependencies-
 
       - run: mvn dependency:go-offline
 
       - save_cache:
           paths:
             - ~/.m2
-
-          key: v1-dependencies-{{ checksum "pom.xml" }}
+          key: v2-dependencies-{{ checksum "pom.xml" }}
 
   running-automation-tests:
     description: "Running automation tests"
     steps:
       - run:
           name: Run tests
-          command: mvn
-            -DxmlSuiteFile=<< pipeline.parameters.suite >>
-            clean test
+          command: mvn -DxmlSuiteFile=<< pipeline.parameters.suite >> clean test
           no_output_timeout: 20m
 
   archive-allure-artifacts:
@@ -62,8 +70,7 @@ commands:
       - run:
           name: Archive artifacts
           when: always
-          command:
-            tar -cvf artifacts-<< pipeline.parameters.suite >>.tar target/;
+          command: tar -cvf artifacts-<< pipeline.parameters.suite >>.tar target/
 
   store-archived-allure-artifacts:
     description: "Upload archived allure artifacts"
@@ -91,7 +98,7 @@ commands:
   send-notification-to-slack-channel:
     description: "Send notification to Slack channel"
     steps:
-       - when:
+      - when:
           condition: << pipeline.parameters.notifyToSlack >>
           steps:
             - slack/status:
@@ -101,14 +108,12 @@ commands:
                 webhook: $SLACK_WEBHOOK
 
 jobs:
-  #There is a custom name of my job. We can change it anytime
   automation-tests-running:
     parameters:
       NightlyRunNotify:
         type: boolean
         default: false
     executor: test-executor
-    #There is all custom names which located under 'Commands' section
     steps:
       - restore-and-save-cache
       - running-automation-tests
@@ -117,7 +122,6 @@ jobs:
       - allure-report-generation
       - store-generated-allure-artifacts
       - send-notification-to-slack-channel
-
 
 workflows:
 
@@ -148,5 +152,5 @@ workflows:
     when: << pipeline.parameters.ApiTrigger >>
     jobs:
       - buid_approval:
-            type: approval
+          type: approval
       - automation-tests-running
