circle ci was updated

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -30,18 +30,31 @@ commands:
   restore-and-save-cache:
     description: "Restore and save cache"
     steps:
+      - run:
+          name: Ensure working directory exists
+          command: mkdir -p ~/SelenideProject
+
+      - checkout  # Upload code before cashing
+
+      - run:
+          name: Verify if pom.xml exists
+          command: |
+            if [ ! -f pom.xml ]; then
+              echo "ERROR: pom.xml not found!"
+              exit 1
+            fi
+
       - restore_cache:
           keys:
-            - v1-dependencies-{{ checksum "pom.xml" }}
-            - v1-dependencies-
+            - v2-dependencies-{{ checksum "pom.xml" }}
+            - v2-dependencies-
 
       - run: mvn dependency:go-offline
 
       - save_cache:
           paths:
             - ~/.m2
-
-          key: v1-dependencies-{{ checksum "pom.xml" }}
+          key: v2-dependencies-{{ checksum "pom.xml" }}
 
   running-automation-tests:
     description: "Running automation tests"
@@ -115,7 +128,6 @@ jobs:
       - store-generated-allure-artifacts
       - send-notification-to-slack-channel
 
-
 workflows:
 
   commit-workflow:
@@ -145,5 +157,5 @@ workflows:
     when: << pipeline.parameters.ApiTrigger >>
     jobs:
       - buid_approval:
-            type: approval
+          type: approval
       - automation-tests-running
